=== maduhu/interop-dfsp-directory/DFSPDirectoryGateway/src/main/api/directory.user.errorResponse.Schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "JSON RPC error response object",
  "description": "JSON-RPC compatible response object for error",
  "properties": {
    "jsonrpc": {
      "enum": [
        "2.0"
      ]
    },
    "id": {
      "type": "string"
    },
    "error": {
      "properties": {
        "code": {
          "description": "Standard code as defined by JSON-RPC. These codes usually are not application errors, but more on protocol or network level.",
          "type": "integer"
        },
        "message": {
          "description": "Technical error message suitable to be logged in application logs. This message is supposed to aid for audit / debug purposes and is visible to system admins",
          "type": "string"
        },
        "errorPrint": {
          "description": "User friendly message translated to the user's language and suitable for displaying to the user that invoked the action",
          "type": "string"
        },
        "type": {
          "type": "string",
          "description": "Application defined error type, usually part of well defined list of error types. The error types should be namespaced similar to the services. The calling app should be able to interpret these types and in some cases provide suitable options for the user to proceed accordingly to the error. For example errors such duplication of data, expired passwords and similar, are usually things that the calling front end could handle."
        }
      },
      "required": [
        "type",
        "code"
      ],
      "type": "object",
      "description": "Presence of this property indicates an error"
    },
    "debug": {
      "properties": {
        "stackInfo": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Provides the calling stack, which should include also the filename and row:column as per browser standard"
        },
        "cause": {
          "type": "object",
          "description": "Any nested errors should be in this property. The nested errors could have their own cause and stackinfo"
        }
      },
      "type": "object",
      "description": "This whole object is included only in non production environment, to aid integration and testing efforts. There could be many properties in the debug object, that give further details, but main idea here is to stick to at least the specified properties as minimum standard."
    }
  },
  "required": [
    "jsonrpc",
    "error",
    "id"
  ]
}

=== maduhu/interop-dfsp-directory/src/main/api/samples/directory.user.errorResponse.Sample.json
{
	"jsonrpc": "2.0",
	"id": "sampleid",
	"error": {
		"type": "parsingerror",
		"code": 400,
		"errorPrint": "The request could not be read by our software.",
		"message": "Parsing error"
	},
	"debug": {
		"cause": {
			"error": {
				"code": 400,
				"message": "An application generated message related to the error",
				"errorPrint": "This is the exception message from the top level exception",
				"type": "parsingerror"
			}
		},
		"stackInfo": ["Callnumber1", "Callnumber2"]
	}
}

=== maduhu/interop-dfsp-directory/DFSPDirectoryGateway/src/main/api/directory.user.errorResponse.Sample.json
{
  "jsonrpc": "2.0",
  "id": "sampleid",
  "error": {
    "type": "parsingerror",
    "code": 400,
    "errorPrint": "The request could not be read by our software.",
    "message": "Parsing error"
  },
  "debug": {
    "cause": {
      "error": {
        "code": 400,
        "message": "One of the properties contained illegal characters",
        "errorPrint": "One of the values provided has invalid characters",
        "type": "parsingerror"
      },
      "id": "sampleid",
      "debug": {
        "stackInfo": [
          "Callnumber1",
          "Callnumber2"
        ]
      }
    }
  }
}
