=== maduhu/interop-dfsp-directory/Projects/dfspdirectorygateway/src/main/api/directory.user.addRequest.Schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "jsonrpc": {
      "enum": ["2.0"]
    },
    "id": {
      "type": "string"
    },
    "method": {
      "type": "string"
    },
    "params": {
      "type": "object",
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "centralURI": {
                "type": "string"
              },
              "dfspURI": {
                "type": "string"
              },
              "currency": {
                "type": "string"
              }
            },
            "required": [
              "centralURI",
              "dfspURI",
              "currency"
            ]
          }
        }
      },
      "required": [
        "users"
      ]
    }
  },
  "required": [
    "jsonrpc",
    "id",
    "method",
    "params"
  ]
}

=== maduhu/interop-dfsp-directory/Projects/dfspdirectorygateway/src/main/api/directory.user.addRequest.Sample.json
{
  "jsonrpc": "2.0",
  "id": "incididunt eiusmod ut ex",
  "method": "directory.user.add",
  "params": {
    "users": [
      {
        "centralURI": "http://userdata.com/bryan",
        "dfspURI": "http://receivingdfsp.com/bryan",
        "currency": "USD"
      },
      {
        "centralURI": "http://userdata.com/joe",
        "dfspURI": "http://receivingdfsp.com/joe",
        "currency": "USD"
      },
      {
        "centralURI": "http://userdata.com/sam",
        "dfspURI": "http://receivingdfsp.com/sam",
        "currency": "INR"
      },
      {
        "centralURI": "http://userdata.com/walter",
        "dfspURI": "http://receivingdfsp.com/walter",
        "currency": "ARS"
      }
    ]
  }
}
